<a href="https://colab.research.google.com/github/FAIZAADNAN/FAIZAADNAN/blob/main/revision_of_semester.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Write a program to create a function which returns square of a number. Call the function to print square root of consecutive 10 numbers.
What are the uses of following functions :
lstrip
rstrip
strip
Write codes to use the above functions


In [ ]:
import math

def square(num):
   return num*num
for i in range(1,11):
  # function call
  result = square(i)
  print("square of" ,i, "=",result)


#function result

square of 1 = 1
square of 2 = 4
square of 3 = 9
square of 4 = 16
square of 5 = 25
square of 6 = 36
square of 7 = 49
square of 8 = 64
square of 9 = 81
square of 10 = 100


In [ ]:
# remove  any strip before and after stripspace
string = "   Hi, faiza!   "
string = string.strip()
print(string)  

# Remove leftspace
string = "   Hi, adnan!   "
string = string.lstrip()
print(string)  

# Remove rightspace
string = "   How , are you!   "
string = string.rstrip()
print(string)  

Hi, faiza!
Hi, adnan!   
   How , are you!


In [ ]:
If-else
Write a Python program to check whether an alphabet is a vowel or consonant



In [ ]:
alphabet = input("enter alphabet: ")
if alphabet in ('a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U'):
    print(alphabet,"is a vowel")
else:
    print(alphabet,"is a consonent")


enter alphabet: a
a is a vowel


In [ ]:
If-elif-else
Take two numbers from the user, compare and print the smaller number.
 Also consider a condition where both the numbers can be same.


In [ ]:
#take input from the user
num1 = int(input("Enter the first number:"))
num2 = int(input("Enter the second number:"))
# Compare the numbers and print the smaller one
if num1 < num2:
  print(num1)
elif num2 < num1:
  print(num2)
else:
  print("Both numbers are equal.")



Enter the first number:10
Enter the second number:8
8


In [ ]:
List type data+ for loop
Write a program to print the all the elements in a list data type using for loop



In [ ]:
data = [1, 2, 3, 4, 5]

for item in data:
  print(item)

1
2
3
4
5


In [ ]:
Dictionary data type
Create a dictionary data-type of a student with name, id and course.
 Write a program to print all the key-value pair in the dictionary. 
 Add another key-value pair called gender to update the dictionary and print the updated dictionary.



In [11]:
student = {"name":"faiza","id": 234,"course": "BSC Computer science"}
print("Display key-value pairs")
for key, value in student.items(): #read all items
   print(f"\nKey: {key}")
   print(f"\nvalue: {value}")
student['gender'] = 'female'
print(student)

Display key-value pairs

Key: name

value: faiza

Key: id

value: 234

Key: course

value: BSC Computer science
{'name': 'faiza', 'id': 234, 'course': 'BSC Computer science', 'gender': 'female'}


In [ ]:
Tuple data type
Declare 2 Tuples comprising of 4 leap years and 4 non leap years
i.	Print tuples
ii.	Concatenate 2 tuples
iii.	Multiple each tuple 3 times
iv.	Compare 2 tuples
v.	Find the length of tuples
vi.	Find the sum of elements in each of the tuples
vii.	Sort the elements in each of the tuples
viii.	Swap the tuples


In [3]:
#integer comprising leap year and non leap year seprately
leap_year = (2024,2028,2032,2036)
non_leap_year = (2023,2025,2026,2027)
print('The List of 4 upcoming leap years:',leap_year[0:5])
print('The List of 4 upcoming leap year:',non_leap_year[0:5])

#concatenate 2 tuples
print('The list of few leap years and non leap years are:\n',leap_year+non_leap_year)
#repeating the number of times by using * operator
print(leap_year*3)
#compare 2 tuples
print(leap_year==non_leap_year)
#length of each tuple
print(len(leap_year))
print(len(non_leap_year))
#sum of elements in tuples
print(sum(leap_year))
print(sum(non_leap_year))
#sort of elements in tuples
print(sorted(leap_year))
print(sorted(non_leap_year))
#swap two tuples
leap_year,non_leap_year=non_leap_year,leap_year
print('upcoming 4 non leap years:',leap_year)
print('upcoming 4 non leap year:',non_leap_year)




The List of 4 upcoming leap years: (2024, 2028, 2032, 2036)
The List of 4 upcoming leap year: (2023, 2025, 2026, 2027)
The list of few leap years and non leap years are:
 (2024, 2028, 2032, 2036, 2023, 2025, 2026, 2027)
(2024, 2028, 2032, 2036, 2024, 2028, 2032, 2036, 2024, 2028, 2032, 2036)
False
4
4
8120
8101
[2024, 2028, 2032, 2036]
[2023, 2025, 2026, 2027]
upcoming 4 non leap years: (2023, 2025, 2026, 2027)
upcoming 4 non leap year: (2024, 2028, 2032, 2036)


In [ ]:
String + for loop
Write a  program to Count the Number of Occurrence of a Character in String


In [4]:
#count the number of the occurence of a character in string
counter = 0
my_string = "classroom"
my_char = "A"
for i in my_string:
   if i == my_char:
      counter += 1
print(counter)


0


In [ ]:
Array
Write a program to create and print Zero, one, Two and multi dimensional array importing NumPy module as array function


In [10]:
import numpy as np
#create 0 dimensional array
arr=np.array(50)
print("zero dimensional array: ",arr)

#create one dimensional array
arr1=np.array([10,20,30,40,50])
print('one dimensional array: ',arr1)
#create two dimensional array
arr2=np.array([[2,4,16],[3,9,81]])
print('two dimensional array:\n ',arr2)
#create 3 dimensional array
arr3=np.array([[[1,1,1,1],[2,2,2,2]],[[3,3,3,3],[4,4,4,4]]])
print('Multi dimensional array:\n',arr3)

zero dimensional array:  50
one dimensional array:  [10 20 30 40 50]
two dimensional array:
  [[ 2  4 16]
 [ 3  9 81]]
Multi dimensional array:
 [[[1 1 1 1]
  [2 2 2 2]]

 [[3 3 3 3]
  [4 4 4 4]]]
